spring:
  application:
    name: network_repairs
  
  datasource:
    url: jdbc:postgresql://localhost:5434/network-repair
    username: tecnicosquito
    password: 123456
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5434/network-repair
    user: tecnicosquito
    password: 123456
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 9090

logging:
  level:
    org:
      hibernate:
        orm:
          connections:
            pooling: DEBUG
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE