server:
  port: 9090

spring:
  application:
    name: network_repairs

  datasource:
    postgresql-db:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5434/network-repairs
      username: pasajerosquito
      password: 123456

  jpa:
    postgres:
      hibernate:
        show_sql: true
        ddl_auto: none
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 21MB

app:
  minio:
    url: http://localhost:9000
    accessKey: admin
    secretKey: 12345678
    bucketName: network-repairs
    region: ec

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
